// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="multi_lms_module_multi_lms_module,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.786000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3,HLS_SYN_LUT=223,HLS_VERSION=2024_2}" *)

module multi_lms_module (
        ap_clk,
        ap_rst_n,
        d_in_TDATA,
        d_in_TVALID,
        d_in_TREADY,
        d_in_TKEEP,
        d_in_TSTRB,
        d_in_TLAST,
        X_in_0_TDATA,
        X_in_0_TVALID,
        X_in_0_TREADY,
        X_in_0_TKEEP,
        X_in_0_TSTRB,
        X_in_0_TLAST,
        X_in_1_TDATA,
        X_in_1_TVALID,
        X_in_1_TREADY,
        X_in_1_TKEEP,
        X_in_1_TSTRB,
        X_in_1_TLAST,
        X_in_2_TDATA,
        X_in_2_TVALID,
        X_in_2_TREADY,
        X_in_2_TKEEP,
        X_in_2_TSTRB,
        X_in_2_TLAST,
        X_in_3_TDATA,
        X_in_3_TVALID,
        X_in_3_TREADY,
        X_in_3_TKEEP,
        X_in_3_TSTRB,
        X_in_3_TLAST,
        X_in_4_TDATA,
        X_in_4_TVALID,
        X_in_4_TREADY,
        X_in_4_TKEEP,
        X_in_4_TSTRB,
        X_in_4_TLAST,
        X_in_5_TDATA,
        X_in_5_TVALID,
        X_in_5_TREADY,
        X_in_5_TKEEP,
        X_in_5_TSTRB,
        X_in_5_TLAST,
        X_in_6_TDATA,
        X_in_6_TVALID,
        X_in_6_TREADY,
        X_in_6_TKEEP,
        X_in_6_TSTRB,
        X_in_6_TLAST,
        output_r_TDATA,
        output_r_TVALID,
        output_r_TREADY,
        output_r_TKEEP,
        output_r_TSTRB,
        output_r_TLAST,
        mu_in
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input  [31:0] d_in_TDATA;
input   d_in_TVALID;
output   d_in_TREADY;
input  [3:0] d_in_TKEEP;
input  [3:0] d_in_TSTRB;
input  [0:0] d_in_TLAST;
input  [31:0] X_in_0_TDATA;
input   X_in_0_TVALID;
output   X_in_0_TREADY;
input  [3:0] X_in_0_TKEEP;
input  [3:0] X_in_0_TSTRB;
input  [0:0] X_in_0_TLAST;
input  [31:0] X_in_1_TDATA;
input   X_in_1_TVALID;
output   X_in_1_TREADY;
input  [3:0] X_in_1_TKEEP;
input  [3:0] X_in_1_TSTRB;
input  [0:0] X_in_1_TLAST;
input  [31:0] X_in_2_TDATA;
input   X_in_2_TVALID;
output   X_in_2_TREADY;
input  [3:0] X_in_2_TKEEP;
input  [3:0] X_in_2_TSTRB;
input  [0:0] X_in_2_TLAST;
input  [31:0] X_in_3_TDATA;
input   X_in_3_TVALID;
output   X_in_3_TREADY;
input  [3:0] X_in_3_TKEEP;
input  [3:0] X_in_3_TSTRB;
input  [0:0] X_in_3_TLAST;
input  [31:0] X_in_4_TDATA;
input   X_in_4_TVALID;
output   X_in_4_TREADY;
input  [3:0] X_in_4_TKEEP;
input  [3:0] X_in_4_TSTRB;
input  [0:0] X_in_4_TLAST;
input  [31:0] X_in_5_TDATA;
input   X_in_5_TVALID;
output   X_in_5_TREADY;
input  [3:0] X_in_5_TKEEP;
input  [3:0] X_in_5_TSTRB;
input  [0:0] X_in_5_TLAST;
input  [31:0] X_in_6_TDATA;
input   X_in_6_TVALID;
output   X_in_6_TREADY;
input  [3:0] X_in_6_TKEEP;
input  [3:0] X_in_6_TSTRB;
input  [0:0] X_in_6_TLAST;
output  [31:0] output_r_TDATA;
output   output_r_TVALID;
input   output_r_TREADY;
output  [3:0] output_r_TKEEP;
output  [3:0] output_r_TSTRB;
output  [0:0] output_r_TLAST;
input  [31:0] mu_in;

 reg    ap_rst_n_inv;
reg    d_in_TDATA_blk_n;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state2;
reg    X_in_0_TDATA_blk_n;
reg    X_in_1_TDATA_blk_n;
reg    X_in_2_TDATA_blk_n;
reg    X_in_3_TDATA_blk_n;
reg    X_in_4_TDATA_blk_n;
reg    X_in_5_TDATA_blk_n;
reg    X_in_6_TDATA_blk_n;
reg    output_r_TDATA_blk_n;
reg    ap_block_state1_pp0_stage0_iter0;
wire    regslice_both_output_r_V_data_V_U_apdone_blk;
reg    ap_block_state2_pp0_stage0_iter1;
wire   [15:0] trunc_ln27_fu_277_p1;
wire   [15:0] trunc_ln30_fu_295_p1;
wire  signed [16:0] sext_ln37_fu_309_p1;
wire  signed [16:0] sext_ln37_1_fu_313_p1;
wire   [16:0] sub_ln37_fu_317_p2;
wire   [0:0] tmp_fu_323_p3;
wire   [0:0] tmp_1_fu_335_p3;
wire   [0:0] xor_ln37_fu_343_p2;
wire   [0:0] and_ln37_fu_349_p2;
wire   [0:0] xor_ln37_1_fu_355_p2;
wire   [15:0] select_ln37_fu_361_p3;
wire   [15:0] trunc_ln37_fu_331_p1;
wire   [15:0] trunc_ln27_1_fu_281_p4;
wire   [15:0] trunc_ln30_1_fu_299_p4;
wire  signed [16:0] sext_ln38_fu_377_p1;
wire  signed [16:0] sext_ln38_1_fu_381_p1;
wire   [16:0] sub_ln38_fu_385_p2;
wire   [0:0] tmp_2_fu_391_p3;
wire   [0:0] tmp_3_fu_403_p3;
wire   [0:0] xor_ln38_fu_411_p2;
wire   [0:0] and_ln38_fu_417_p2;
wire   [0:0] xor_ln38_1_fu_423_p2;
wire   [15:0] select_ln38_fu_429_p3;
wire   [15:0] trunc_ln38_fu_399_p1;
wire   [15:0] out_tmp_data_M_imag_fu_437_p3;
wire   [15:0] out_tmp_data_M_real_fu_369_p3;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
wire    regslice_both_d_in_V_data_V_U_apdone_blk;
wire   [31:0] d_in_TDATA_int_regslice;
wire    d_in_TVALID_int_regslice;
reg    d_in_TREADY_int_regslice;
wire    regslice_both_d_in_V_data_V_U_ack_in;
wire    regslice_both_d_in_V_keep_V_U_apdone_blk;
wire   [3:0] d_in_TKEEP_int_regslice;
wire    regslice_both_d_in_V_keep_V_U_vld_out;
wire    regslice_both_d_in_V_keep_V_U_ack_in;
wire    regslice_both_d_in_V_strb_V_U_apdone_blk;
wire   [3:0] d_in_TSTRB_int_regslice;
wire    regslice_both_d_in_V_strb_V_U_vld_out;
wire    regslice_both_d_in_V_strb_V_U_ack_in;
wire    regslice_both_d_in_V_last_V_U_apdone_blk;
wire   [0:0] d_in_TLAST_int_regslice;
wire    regslice_both_d_in_V_last_V_U_vld_out;
wire    regslice_both_d_in_V_last_V_U_ack_in;
wire    regslice_both_X_in_0_V_data_V_U_apdone_blk;
wire   [31:0] X_in_0_TDATA_int_regslice;
wire    X_in_0_TVALID_int_regslice;
reg    X_in_0_TREADY_int_regslice;
wire    regslice_both_X_in_0_V_data_V_U_ack_in;
wire    regslice_both_X_in_0_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_0_TKEEP_int_regslice;
wire    regslice_both_X_in_0_V_keep_V_U_vld_out;
wire    regslice_both_X_in_0_V_keep_V_U_ack_in;
wire    regslice_both_X_in_0_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_0_TSTRB_int_regslice;
wire    regslice_both_X_in_0_V_strb_V_U_vld_out;
wire    regslice_both_X_in_0_V_strb_V_U_ack_in;
wire    regslice_both_X_in_0_V_last_V_U_apdone_blk;
wire   [0:0] X_in_0_TLAST_int_regslice;
wire    regslice_both_X_in_0_V_last_V_U_vld_out;
wire    regslice_both_X_in_0_V_last_V_U_ack_in;
wire    regslice_both_X_in_1_V_data_V_U_apdone_blk;
wire   [31:0] X_in_1_TDATA_int_regslice;
wire    X_in_1_TVALID_int_regslice;
reg    X_in_1_TREADY_int_regslice;
wire    regslice_both_X_in_1_V_data_V_U_ack_in;
wire    regslice_both_X_in_1_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_1_TKEEP_int_regslice;
wire    regslice_both_X_in_1_V_keep_V_U_vld_out;
wire    regslice_both_X_in_1_V_keep_V_U_ack_in;
wire    regslice_both_X_in_1_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_1_TSTRB_int_regslice;
wire    regslice_both_X_in_1_V_strb_V_U_vld_out;
wire    regslice_both_X_in_1_V_strb_V_U_ack_in;
wire    regslice_both_X_in_1_V_last_V_U_apdone_blk;
wire   [0:0] X_in_1_TLAST_int_regslice;
wire    regslice_both_X_in_1_V_last_V_U_vld_out;
wire    regslice_both_X_in_1_V_last_V_U_ack_in;
wire    regslice_both_X_in_2_V_data_V_U_apdone_blk;
wire   [31:0] X_in_2_TDATA_int_regslice;
wire    X_in_2_TVALID_int_regslice;
reg    X_in_2_TREADY_int_regslice;
wire    regslice_both_X_in_2_V_data_V_U_ack_in;
wire    regslice_both_X_in_2_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_2_TKEEP_int_regslice;
wire    regslice_both_X_in_2_V_keep_V_U_vld_out;
wire    regslice_both_X_in_2_V_keep_V_U_ack_in;
wire    regslice_both_X_in_2_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_2_TSTRB_int_regslice;
wire    regslice_both_X_in_2_V_strb_V_U_vld_out;
wire    regslice_both_X_in_2_V_strb_V_U_ack_in;
wire    regslice_both_X_in_2_V_last_V_U_apdone_blk;
wire   [0:0] X_in_2_TLAST_int_regslice;
wire    regslice_both_X_in_2_V_last_V_U_vld_out;
wire    regslice_both_X_in_2_V_last_V_U_ack_in;
wire    regslice_both_X_in_3_V_data_V_U_apdone_blk;
wire   [31:0] X_in_3_TDATA_int_regslice;
wire    X_in_3_TVALID_int_regslice;
reg    X_in_3_TREADY_int_regslice;
wire    regslice_both_X_in_3_V_data_V_U_ack_in;
wire    regslice_both_X_in_3_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_3_TKEEP_int_regslice;
wire    regslice_both_X_in_3_V_keep_V_U_vld_out;
wire    regslice_both_X_in_3_V_keep_V_U_ack_in;
wire    regslice_both_X_in_3_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_3_TSTRB_int_regslice;
wire    regslice_both_X_in_3_V_strb_V_U_vld_out;
wire    regslice_both_X_in_3_V_strb_V_U_ack_in;
wire    regslice_both_X_in_3_V_last_V_U_apdone_blk;
wire   [0:0] X_in_3_TLAST_int_regslice;
wire    regslice_both_X_in_3_V_last_V_U_vld_out;
wire    regslice_both_X_in_3_V_last_V_U_ack_in;
wire    regslice_both_X_in_4_V_data_V_U_apdone_blk;
wire   [31:0] X_in_4_TDATA_int_regslice;
wire    X_in_4_TVALID_int_regslice;
reg    X_in_4_TREADY_int_regslice;
wire    regslice_both_X_in_4_V_data_V_U_ack_in;
wire    regslice_both_X_in_4_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_4_TKEEP_int_regslice;
wire    regslice_both_X_in_4_V_keep_V_U_vld_out;
wire    regslice_both_X_in_4_V_keep_V_U_ack_in;
wire    regslice_both_X_in_4_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_4_TSTRB_int_regslice;
wire    regslice_both_X_in_4_V_strb_V_U_vld_out;
wire    regslice_both_X_in_4_V_strb_V_U_ack_in;
wire    regslice_both_X_in_4_V_last_V_U_apdone_blk;
wire   [0:0] X_in_4_TLAST_int_regslice;
wire    regslice_both_X_in_4_V_last_V_U_vld_out;
wire    regslice_both_X_in_4_V_last_V_U_ack_in;
wire    regslice_both_X_in_5_V_data_V_U_apdone_blk;
wire   [31:0] X_in_5_TDATA_int_regslice;
wire    X_in_5_TVALID_int_regslice;
reg    X_in_5_TREADY_int_regslice;
wire    regslice_both_X_in_5_V_data_V_U_ack_in;
wire    regslice_both_X_in_5_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_5_TKEEP_int_regslice;
wire    regslice_both_X_in_5_V_keep_V_U_vld_out;
wire    regslice_both_X_in_5_V_keep_V_U_ack_in;
wire    regslice_both_X_in_5_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_5_TSTRB_int_regslice;
wire    regslice_both_X_in_5_V_strb_V_U_vld_out;
wire    regslice_both_X_in_5_V_strb_V_U_ack_in;
wire    regslice_both_X_in_5_V_last_V_U_apdone_blk;
wire   [0:0] X_in_5_TLAST_int_regslice;
wire    regslice_both_X_in_5_V_last_V_U_vld_out;
wire    regslice_both_X_in_5_V_last_V_U_ack_in;
wire    regslice_both_X_in_6_V_data_V_U_apdone_blk;
wire   [31:0] X_in_6_TDATA_int_regslice;
wire    X_in_6_TVALID_int_regslice;
reg    X_in_6_TREADY_int_regslice;
wire    regslice_both_X_in_6_V_data_V_U_ack_in;
wire    regslice_both_X_in_6_V_keep_V_U_apdone_blk;
wire   [3:0] X_in_6_TKEEP_int_regslice;
wire    regslice_both_X_in_6_V_keep_V_U_vld_out;
wire    regslice_both_X_in_6_V_keep_V_U_ack_in;
wire    regslice_both_X_in_6_V_strb_V_U_apdone_blk;
wire   [3:0] X_in_6_TSTRB_int_regslice;
wire    regslice_both_X_in_6_V_strb_V_U_vld_out;
wire    regslice_both_X_in_6_V_strb_V_U_ack_in;
wire    regslice_both_X_in_6_V_last_V_U_apdone_blk;
wire   [0:0] X_in_6_TLAST_int_regslice;
wire    regslice_both_X_in_6_V_last_V_U_vld_out;
wire    regslice_both_X_in_6_V_last_V_U_ack_in;
wire   [31:0] output_r_TDATA_int_regslice;
reg    output_r_TVALID_int_regslice;
wire    output_r_TREADY_int_regslice;
wire    regslice_both_output_r_V_data_V_U_vld_out;
wire    regslice_both_output_r_V_keep_V_U_apdone_blk;
wire    regslice_both_output_r_V_keep_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_keep_V_U_vld_out;
wire    regslice_both_output_r_V_strb_V_U_apdone_blk;
wire    regslice_both_output_r_V_strb_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_strb_V_U_vld_out;
wire    regslice_both_output_r_V_last_V_U_apdone_blk;
wire    regslice_both_output_r_V_last_V_U_ack_in_dummy;
wire    regslice_both_output_r_V_last_V_U_vld_out;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
end

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_d_in_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TDATA),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_data_V_U_ack_in),
    .data_out(d_in_TDATA_int_regslice),
    .vld_out(d_in_TVALID_int_regslice),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_d_in_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TKEEP),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_keep_V_U_ack_in),
    .data_out(d_in_TKEEP_int_regslice),
    .vld_out(regslice_both_d_in_V_keep_V_U_vld_out),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_d_in_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TSTRB),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_strb_V_U_ack_in),
    .data_out(d_in_TSTRB_int_regslice),
    .vld_out(regslice_both_d_in_V_strb_V_U_vld_out),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_d_in_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TLAST),
    .vld_in(d_in_TVALID),
    .ack_in(regslice_both_d_in_V_last_V_U_ack_in),
    .data_out(d_in_TLAST_int_regslice),
    .vld_out(regslice_both_d_in_V_last_V_U_vld_out),
    .ack_out(d_in_TREADY_int_regslice),
    .apdone_blk(regslice_both_d_in_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_0_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_0_TDATA),
    .vld_in(X_in_0_TVALID),
    .ack_in(regslice_both_X_in_0_V_data_V_U_ack_in),
    .data_out(X_in_0_TDATA_int_regslice),
    .vld_out(X_in_0_TVALID_int_regslice),
    .ack_out(X_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_0_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_0_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_0_TKEEP),
    .vld_in(X_in_0_TVALID),
    .ack_in(regslice_both_X_in_0_V_keep_V_U_ack_in),
    .data_out(X_in_0_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_0_V_keep_V_U_vld_out),
    .ack_out(X_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_0_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_0_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_0_TSTRB),
    .vld_in(X_in_0_TVALID),
    .ack_in(regslice_both_X_in_0_V_strb_V_U_ack_in),
    .data_out(X_in_0_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_0_V_strb_V_U_vld_out),
    .ack_out(X_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_0_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_0_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_0_TLAST),
    .vld_in(X_in_0_TVALID),
    .ack_in(regslice_both_X_in_0_V_last_V_U_ack_in),
    .data_out(X_in_0_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_0_V_last_V_U_vld_out),
    .ack_out(X_in_0_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_0_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_1_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_1_TDATA),
    .vld_in(X_in_1_TVALID),
    .ack_in(regslice_both_X_in_1_V_data_V_U_ack_in),
    .data_out(X_in_1_TDATA_int_regslice),
    .vld_out(X_in_1_TVALID_int_regslice),
    .ack_out(X_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_1_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_1_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_1_TKEEP),
    .vld_in(X_in_1_TVALID),
    .ack_in(regslice_both_X_in_1_V_keep_V_U_ack_in),
    .data_out(X_in_1_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_1_V_keep_V_U_vld_out),
    .ack_out(X_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_1_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_1_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_1_TSTRB),
    .vld_in(X_in_1_TVALID),
    .ack_in(regslice_both_X_in_1_V_strb_V_U_ack_in),
    .data_out(X_in_1_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_1_V_strb_V_U_vld_out),
    .ack_out(X_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_1_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_1_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_1_TLAST),
    .vld_in(X_in_1_TVALID),
    .ack_in(regslice_both_X_in_1_V_last_V_U_ack_in),
    .data_out(X_in_1_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_1_V_last_V_U_vld_out),
    .ack_out(X_in_1_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_1_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_2_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_2_TDATA),
    .vld_in(X_in_2_TVALID),
    .ack_in(regslice_both_X_in_2_V_data_V_U_ack_in),
    .data_out(X_in_2_TDATA_int_regslice),
    .vld_out(X_in_2_TVALID_int_regslice),
    .ack_out(X_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_2_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_2_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_2_TKEEP),
    .vld_in(X_in_2_TVALID),
    .ack_in(regslice_both_X_in_2_V_keep_V_U_ack_in),
    .data_out(X_in_2_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_2_V_keep_V_U_vld_out),
    .ack_out(X_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_2_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_2_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_2_TSTRB),
    .vld_in(X_in_2_TVALID),
    .ack_in(regslice_both_X_in_2_V_strb_V_U_ack_in),
    .data_out(X_in_2_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_2_V_strb_V_U_vld_out),
    .ack_out(X_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_2_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_2_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_2_TLAST),
    .vld_in(X_in_2_TVALID),
    .ack_in(regslice_both_X_in_2_V_last_V_U_ack_in),
    .data_out(X_in_2_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_2_V_last_V_U_vld_out),
    .ack_out(X_in_2_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_2_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_3_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_3_TDATA),
    .vld_in(X_in_3_TVALID),
    .ack_in(regslice_both_X_in_3_V_data_V_U_ack_in),
    .data_out(X_in_3_TDATA_int_regslice),
    .vld_out(X_in_3_TVALID_int_regslice),
    .ack_out(X_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_3_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_3_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_3_TKEEP),
    .vld_in(X_in_3_TVALID),
    .ack_in(regslice_both_X_in_3_V_keep_V_U_ack_in),
    .data_out(X_in_3_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_3_V_keep_V_U_vld_out),
    .ack_out(X_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_3_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_3_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_3_TSTRB),
    .vld_in(X_in_3_TVALID),
    .ack_in(regslice_both_X_in_3_V_strb_V_U_ack_in),
    .data_out(X_in_3_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_3_V_strb_V_U_vld_out),
    .ack_out(X_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_3_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_3_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_3_TLAST),
    .vld_in(X_in_3_TVALID),
    .ack_in(regslice_both_X_in_3_V_last_V_U_ack_in),
    .data_out(X_in_3_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_3_V_last_V_U_vld_out),
    .ack_out(X_in_3_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_3_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_4_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_4_TDATA),
    .vld_in(X_in_4_TVALID),
    .ack_in(regslice_both_X_in_4_V_data_V_U_ack_in),
    .data_out(X_in_4_TDATA_int_regslice),
    .vld_out(X_in_4_TVALID_int_regslice),
    .ack_out(X_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_4_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_4_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_4_TKEEP),
    .vld_in(X_in_4_TVALID),
    .ack_in(regslice_both_X_in_4_V_keep_V_U_ack_in),
    .data_out(X_in_4_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_4_V_keep_V_U_vld_out),
    .ack_out(X_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_4_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_4_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_4_TSTRB),
    .vld_in(X_in_4_TVALID),
    .ack_in(regslice_both_X_in_4_V_strb_V_U_ack_in),
    .data_out(X_in_4_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_4_V_strb_V_U_vld_out),
    .ack_out(X_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_4_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_4_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_4_TLAST),
    .vld_in(X_in_4_TVALID),
    .ack_in(regslice_both_X_in_4_V_last_V_U_ack_in),
    .data_out(X_in_4_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_4_V_last_V_U_vld_out),
    .ack_out(X_in_4_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_4_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_5_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_5_TDATA),
    .vld_in(X_in_5_TVALID),
    .ack_in(regslice_both_X_in_5_V_data_V_U_ack_in),
    .data_out(X_in_5_TDATA_int_regslice),
    .vld_out(X_in_5_TVALID_int_regslice),
    .ack_out(X_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_5_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_5_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_5_TKEEP),
    .vld_in(X_in_5_TVALID),
    .ack_in(regslice_both_X_in_5_V_keep_V_U_ack_in),
    .data_out(X_in_5_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_5_V_keep_V_U_vld_out),
    .ack_out(X_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_5_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_5_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_5_TSTRB),
    .vld_in(X_in_5_TVALID),
    .ack_in(regslice_both_X_in_5_V_strb_V_U_ack_in),
    .data_out(X_in_5_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_5_V_strb_V_U_vld_out),
    .ack_out(X_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_5_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_5_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_5_TLAST),
    .vld_in(X_in_5_TVALID),
    .ack_in(regslice_both_X_in_5_V_last_V_U_ack_in),
    .data_out(X_in_5_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_5_V_last_V_U_vld_out),
    .ack_out(X_in_5_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_5_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_X_in_6_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_6_TDATA),
    .vld_in(X_in_6_TVALID),
    .ack_in(regslice_both_X_in_6_V_data_V_U_ack_in),
    .data_out(X_in_6_TDATA_int_regslice),
    .vld_out(X_in_6_TVALID_int_regslice),
    .ack_out(X_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_6_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_6_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_6_TKEEP),
    .vld_in(X_in_6_TVALID),
    .ack_in(regslice_both_X_in_6_V_keep_V_U_ack_in),
    .data_out(X_in_6_TKEEP_int_regslice),
    .vld_out(regslice_both_X_in_6_V_keep_V_U_vld_out),
    .ack_out(X_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_6_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_X_in_6_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_6_TSTRB),
    .vld_in(X_in_6_TVALID),
    .ack_in(regslice_both_X_in_6_V_strb_V_U_ack_in),
    .data_out(X_in_6_TSTRB_int_regslice),
    .vld_out(regslice_both_X_in_6_V_strb_V_U_vld_out),
    .ack_out(X_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_6_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_X_in_6_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(X_in_6_TLAST),
    .vld_in(X_in_6_TVALID),
    .ack_in(regslice_both_X_in_6_V_last_V_U_ack_in),
    .data_out(X_in_6_TLAST_int_regslice),
    .vld_out(regslice_both_X_in_6_V_last_V_U_vld_out),
    .ack_out(X_in_6_TREADY_int_regslice),
    .apdone_blk(regslice_both_X_in_6_V_last_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 32 ))
regslice_both_output_r_V_data_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(output_r_TDATA_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(output_r_TREADY_int_regslice),
    .data_out(output_r_TDATA),
    .vld_out(regslice_both_output_r_V_data_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_data_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_keep_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TKEEP_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_keep_V_U_ack_in_dummy),
    .data_out(output_r_TKEEP),
    .vld_out(regslice_both_output_r_V_keep_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_keep_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 4 ))
regslice_both_output_r_V_strb_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TSTRB_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_strb_V_U_ack_in_dummy),
    .data_out(output_r_TSTRB),
    .vld_out(regslice_both_output_r_V_strb_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_strb_V_U_apdone_blk)
);

multi_lms_module_regslice_both #(
    .DataWidth( 1 ))
regslice_both_output_r_V_last_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(d_in_TLAST_int_regslice),
    .vld_in(output_r_TVALID_int_regslice),
    .ack_in(regslice_both_output_r_V_last_V_U_ack_in_dummy),
    .data_out(output_r_TLAST),
    .vld_out(regslice_both_output_r_V_last_V_U_vld_out),
    .ack_out(output_r_TREADY),
    .apdone_blk(regslice_both_output_r_V_last_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_0_TDATA_blk_n = X_in_0_TVALID_int_regslice;
    end else begin
        X_in_0_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_0_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_0_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_1_TDATA_blk_n = X_in_1_TVALID_int_regslice;
    end else begin
        X_in_1_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_1_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_1_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_2_TDATA_blk_n = X_in_2_TVALID_int_regslice;
    end else begin
        X_in_2_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_2_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_2_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_3_TDATA_blk_n = X_in_3_TVALID_int_regslice;
    end else begin
        X_in_3_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_3_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_3_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_4_TDATA_blk_n = X_in_4_TVALID_int_regslice;
    end else begin
        X_in_4_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_4_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_4_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_5_TDATA_blk_n = X_in_5_TVALID_int_regslice;
    end else begin
        X_in_5_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_5_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_5_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        X_in_6_TDATA_blk_n = X_in_6_TVALID_int_regslice;
    end else begin
        X_in_6_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        X_in_6_TREADY_int_regslice = 1'b1;
    end else begin
        X_in_6_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state2_pp0_stage0_iter1)) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_iter0_fsm_state1)) begin
        d_in_TDATA_blk_n = d_in_TVALID_int_regslice;
    end else begin
        d_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        d_in_TREADY_int_regslice = 1'b1;
    end else begin
        d_in_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state2) | (1'b1 == ap_CS_iter0_fsm_state1))) begin
        output_r_TDATA_blk_n = output_r_TREADY_int_regslice;
    end else begin
        output_r_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        output_r_TVALID_int_regslice = 1'b1;
    end else begin
        output_r_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if (((1'b0 == ap_block_state2_pp0_stage0_iter1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if (((1'b0 == ap_block_state2_pp0_stage0_iter1) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_iter0_fsm_state1))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | ((1'b1 == ap_block_state2_pp0_stage0_iter1) & (1'b1 == ap_CS_iter1_fsm_state2))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign X_in_0_TREADY = regslice_both_X_in_0_V_data_V_U_ack_in;

assign X_in_1_TREADY = regslice_both_X_in_1_V_data_V_U_ack_in;

assign X_in_2_TREADY = regslice_both_X_in_2_V_data_V_U_ack_in;

assign X_in_3_TREADY = regslice_both_X_in_3_V_data_V_U_ack_in;

assign X_in_4_TREADY = regslice_both_X_in_4_V_data_V_U_ack_in;

assign X_in_5_TREADY = regslice_both_X_in_5_V_data_V_U_ack_in;

assign X_in_6_TREADY = regslice_both_X_in_6_V_data_V_U_ack_in;

assign and_ln37_fu_349_p2 = (xor_ln37_fu_343_p2 & tmp_1_fu_335_p3);

assign and_ln38_fu_417_p2 = (xor_ln38_fu_411_p2 & tmp_3_fu_403_p3);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((output_r_TREADY_int_regslice == 1'b0) | (1'b0 == X_in_6_TVALID_int_regslice) | (1'b0 == X_in_5_TVALID_int_regslice) | (1'b0 == X_in_4_TVALID_int_regslice) | (1'b0 == X_in_3_TVALID_int_regslice) | (1'b0 == X_in_2_TVALID_int_regslice) | (1'b0 == X_in_1_TVALID_int_regslice) | (1'b0 == X_in_0_TVALID_int_regslice) | (d_in_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((output_r_TREADY_int_regslice == 1'b0) | (regslice_both_output_r_V_data_V_U_apdone_blk == 1'b1));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign d_in_TREADY = regslice_both_d_in_V_data_V_U_ack_in;

assign out_tmp_data_M_imag_fu_437_p3 = ((xor_ln38_1_fu_423_p2[0:0] == 1'b1) ? select_ln38_fu_429_p3 : trunc_ln38_fu_399_p1);

assign out_tmp_data_M_real_fu_369_p3 = ((xor_ln37_1_fu_355_p2[0:0] == 1'b1) ? select_ln37_fu_361_p3 : trunc_ln37_fu_331_p1);

assign output_r_TDATA_int_regslice = {{out_tmp_data_M_imag_fu_437_p3}, {out_tmp_data_M_real_fu_369_p3}};

assign output_r_TVALID = regslice_both_output_r_V_data_V_U_vld_out;

assign select_ln37_fu_361_p3 = ((and_ln37_fu_349_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign select_ln38_fu_429_p3 = ((and_ln38_fu_417_p2[0:0] == 1'b1) ? 16'd32767 : 16'd32768);

assign sext_ln37_1_fu_313_p1 = $signed(trunc_ln30_fu_295_p1);

assign sext_ln37_fu_309_p1 = $signed(trunc_ln27_fu_277_p1);

assign sext_ln38_1_fu_381_p1 = $signed(trunc_ln30_1_fu_299_p4);

assign sext_ln38_fu_377_p1 = $signed(trunc_ln27_1_fu_281_p4);

assign sub_ln37_fu_317_p2 = ($signed(sext_ln37_fu_309_p1) - $signed(sext_ln37_1_fu_313_p1));

assign sub_ln38_fu_385_p2 = ($signed(sext_ln38_fu_377_p1) - $signed(sext_ln38_1_fu_381_p1));

assign tmp_1_fu_335_p3 = sub_ln37_fu_317_p2[32'd15];

assign tmp_2_fu_391_p3 = sub_ln38_fu_385_p2[32'd16];

assign tmp_3_fu_403_p3 = sub_ln38_fu_385_p2[32'd15];

assign tmp_fu_323_p3 = sub_ln37_fu_317_p2[32'd16];

assign trunc_ln27_1_fu_281_p4 = {{d_in_TDATA_int_regslice[31:16]}};

assign trunc_ln27_fu_277_p1 = d_in_TDATA_int_regslice[15:0];

assign trunc_ln30_1_fu_299_p4 = {{X_in_0_TDATA_int_regslice[31:16]}};

assign trunc_ln30_fu_295_p1 = X_in_0_TDATA_int_regslice[15:0];

assign trunc_ln37_fu_331_p1 = sub_ln37_fu_317_p2[15:0];

assign trunc_ln38_fu_399_p1 = sub_ln38_fu_385_p2[15:0];

assign xor_ln37_1_fu_355_p2 = (tmp_fu_323_p3 ^ tmp_1_fu_335_p3);

assign xor_ln37_fu_343_p2 = (tmp_fu_323_p3 ^ 1'd1);

assign xor_ln38_1_fu_423_p2 = (tmp_3_fu_403_p3 ^ tmp_2_fu_391_p3);

assign xor_ln38_fu_411_p2 = (tmp_2_fu_391_p3 ^ 1'd1);

endmodule //multi_lms_module
