-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity multi_lms_module is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    d_in_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    d_in_TVALID : IN STD_LOGIC;
    d_in_TREADY : OUT STD_LOGIC;
    d_in_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    d_in_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    d_in_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_0_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_0_TVALID : IN STD_LOGIC;
    X_in_0_TREADY : OUT STD_LOGIC;
    X_in_0_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_0_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_0_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_1_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_1_TVALID : IN STD_LOGIC;
    X_in_1_TREADY : OUT STD_LOGIC;
    X_in_1_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_1_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_1_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_2_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_2_TVALID : IN STD_LOGIC;
    X_in_2_TREADY : OUT STD_LOGIC;
    X_in_2_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_2_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_2_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_3_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_3_TVALID : IN STD_LOGIC;
    X_in_3_TREADY : OUT STD_LOGIC;
    X_in_3_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_3_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_3_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_4_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_4_TVALID : IN STD_LOGIC;
    X_in_4_TREADY : OUT STD_LOGIC;
    X_in_4_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_4_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_4_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_5_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_5_TVALID : IN STD_LOGIC;
    X_in_5_TREADY : OUT STD_LOGIC;
    X_in_5_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_5_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_5_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    X_in_6_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    X_in_6_TVALID : IN STD_LOGIC;
    X_in_6_TREADY : OUT STD_LOGIC;
    X_in_6_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_6_TSTRB : IN STD_LOGIC_VECTOR (3 downto 0);
    X_in_6_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    output_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    output_r_TVALID : OUT STD_LOGIC;
    output_r_TREADY : IN STD_LOGIC;
    output_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TSTRB : OUT STD_LOGIC_VECTOR (3 downto 0);
    output_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0);
    mu_in : IN STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of multi_lms_module is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "multi_lms_module_multi_lms_module,hls_ip_2024_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=5.000000,HLS_INPUT_ARCH=pipeline,HLS_SYN_CLOCK=1.786000,HLS_SYN_LAT=1,HLS_SYN_TPT=1,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=3,HLS_SYN_LUT=223,HLS_VERSION=2024_2}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_ST_iter1_fsm_state2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_1F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000011111";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv16_7FFF : STD_LOGIC_VECTOR (15 downto 0) := "0111111111111111";
    constant ap_const_lv16_8000 : STD_LOGIC_VECTOR (15 downto 0) := "1000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;

    signal ap_rst_n_inv : STD_LOGIC;
    signal d_in_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0) := "01";
    signal ap_CS_iter1_fsm_state2 : STD_LOGIC;
    signal X_in_0_TDATA_blk_n : STD_LOGIC;
    signal X_in_1_TDATA_blk_n : STD_LOGIC;
    signal X_in_2_TDATA_blk_n : STD_LOGIC;
    signal X_in_3_TDATA_blk_n : STD_LOGIC;
    signal X_in_4_TDATA_blk_n : STD_LOGIC;
    signal X_in_5_TDATA_blk_n : STD_LOGIC;
    signal X_in_6_TDATA_blk_n : STD_LOGIC;
    signal output_r_TDATA_blk_n : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal regslice_both_output_r_V_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal trunc_ln27_fu_277_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln30_fu_295_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln37_fu_309_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln37_1_fu_313_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln37_fu_317_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_fu_323_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_1_fu_335_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_fu_343_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln37_fu_349_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln37_1_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln37_fu_361_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln37_fu_331_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln27_1_fu_281_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln30_1_fu_299_p4 : STD_LOGIC_VECTOR (15 downto 0);
    signal sext_ln38_fu_377_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sext_ln38_1_fu_381_p1 : STD_LOGIC_VECTOR (16 downto 0);
    signal sub_ln38_fu_385_p2 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_2_fu_391_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_fu_403_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln38_fu_411_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln38_fu_417_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln38_1_fu_423_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln38_fu_429_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal trunc_ln38_fu_399_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_tmp_data_M_imag_fu_437_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal out_tmp_data_M_real_fu_369_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state2_blk : STD_LOGIC;
    signal regslice_both_d_in_V_data_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal d_in_TVALID_int_regslice : STD_LOGIC;
    signal d_in_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_d_in_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_d_in_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_d_in_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_d_in_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_d_in_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_d_in_V_last_V_U_apdone_blk : STD_LOGIC;
    signal d_in_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_d_in_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_d_in_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_0_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_0_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_0_TVALID_int_regslice : STD_LOGIC;
    signal X_in_0_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_0_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_0_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_0_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_0_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_0_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_0_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_0_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_0_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_0_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_0_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_0_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_0_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_0_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_1_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_1_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_1_TVALID_int_regslice : STD_LOGIC;
    signal X_in_1_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_1_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_1_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_1_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_1_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_1_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_1_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_1_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_1_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_1_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_1_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_1_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_1_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_1_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_2_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_2_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_2_TVALID_int_regslice : STD_LOGIC;
    signal X_in_2_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_2_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_2_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_2_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_2_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_2_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_2_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_2_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_2_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_2_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_2_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_2_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_2_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_2_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_3_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_3_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_3_TVALID_int_regslice : STD_LOGIC;
    signal X_in_3_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_3_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_3_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_3_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_3_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_3_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_3_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_3_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_3_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_3_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_3_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_3_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_3_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_3_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_4_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_4_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_4_TVALID_int_regslice : STD_LOGIC;
    signal X_in_4_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_4_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_4_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_4_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_4_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_4_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_4_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_4_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_4_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_4_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_4_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_4_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_4_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_4_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_5_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_5_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_5_TVALID_int_regslice : STD_LOGIC;
    signal X_in_5_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_5_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_5_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_5_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_5_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_5_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_5_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_5_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_5_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_5_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_5_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_5_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_5_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_5_V_last_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_6_V_data_V_U_apdone_blk : STD_LOGIC;
    signal X_in_6_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal X_in_6_TVALID_int_regslice : STD_LOGIC;
    signal X_in_6_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_X_in_6_V_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_6_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal X_in_6_TKEEP_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_6_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_6_V_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_6_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal X_in_6_TSTRB_int_regslice : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_X_in_6_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_6_V_strb_V_U_ack_in : STD_LOGIC;
    signal regslice_both_X_in_6_V_last_V_U_apdone_blk : STD_LOGIC;
    signal X_in_6_TLAST_int_regslice : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_X_in_6_V_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_X_in_6_V_last_V_U_ack_in : STD_LOGIC;
    signal output_r_TDATA_int_regslice : STD_LOGIC_VECTOR (31 downto 0);
    signal output_r_TVALID_int_regslice : STD_LOGIC;
    signal output_r_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_output_r_V_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_strb_V_U_vld_out : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_output_r_V_last_V_U_vld_out : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component multi_lms_module_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_d_in_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TDATA,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_data_V_U_ack_in,
        data_out => d_in_TDATA_int_regslice,
        vld_out => d_in_TVALID_int_regslice,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_data_V_U_apdone_blk);

    regslice_both_d_in_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TKEEP,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_keep_V_U_ack_in,
        data_out => d_in_TKEEP_int_regslice,
        vld_out => regslice_both_d_in_V_keep_V_U_vld_out,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_keep_V_U_apdone_blk);

    regslice_both_d_in_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TSTRB,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_strb_V_U_ack_in,
        data_out => d_in_TSTRB_int_regslice,
        vld_out => regslice_both_d_in_V_strb_V_U_vld_out,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_strb_V_U_apdone_blk);

    regslice_both_d_in_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TLAST,
        vld_in => d_in_TVALID,
        ack_in => regslice_both_d_in_V_last_V_U_ack_in,
        data_out => d_in_TLAST_int_regslice,
        vld_out => regslice_both_d_in_V_last_V_U_vld_out,
        ack_out => d_in_TREADY_int_regslice,
        apdone_blk => regslice_both_d_in_V_last_V_U_apdone_blk);

    regslice_both_X_in_0_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_0_TDATA,
        vld_in => X_in_0_TVALID,
        ack_in => regslice_both_X_in_0_V_data_V_U_ack_in,
        data_out => X_in_0_TDATA_int_regslice,
        vld_out => X_in_0_TVALID_int_regslice,
        ack_out => X_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_0_V_data_V_U_apdone_blk);

    regslice_both_X_in_0_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_0_TKEEP,
        vld_in => X_in_0_TVALID,
        ack_in => regslice_both_X_in_0_V_keep_V_U_ack_in,
        data_out => X_in_0_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_0_V_keep_V_U_vld_out,
        ack_out => X_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_0_V_keep_V_U_apdone_blk);

    regslice_both_X_in_0_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_0_TSTRB,
        vld_in => X_in_0_TVALID,
        ack_in => regslice_both_X_in_0_V_strb_V_U_ack_in,
        data_out => X_in_0_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_0_V_strb_V_U_vld_out,
        ack_out => X_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_0_V_strb_V_U_apdone_blk);

    regslice_both_X_in_0_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_0_TLAST,
        vld_in => X_in_0_TVALID,
        ack_in => regslice_both_X_in_0_V_last_V_U_ack_in,
        data_out => X_in_0_TLAST_int_regslice,
        vld_out => regslice_both_X_in_0_V_last_V_U_vld_out,
        ack_out => X_in_0_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_0_V_last_V_U_apdone_blk);

    regslice_both_X_in_1_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_1_TDATA,
        vld_in => X_in_1_TVALID,
        ack_in => regslice_both_X_in_1_V_data_V_U_ack_in,
        data_out => X_in_1_TDATA_int_regslice,
        vld_out => X_in_1_TVALID_int_regslice,
        ack_out => X_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_1_V_data_V_U_apdone_blk);

    regslice_both_X_in_1_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_1_TKEEP,
        vld_in => X_in_1_TVALID,
        ack_in => regslice_both_X_in_1_V_keep_V_U_ack_in,
        data_out => X_in_1_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_1_V_keep_V_U_vld_out,
        ack_out => X_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_1_V_keep_V_U_apdone_blk);

    regslice_both_X_in_1_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_1_TSTRB,
        vld_in => X_in_1_TVALID,
        ack_in => regslice_both_X_in_1_V_strb_V_U_ack_in,
        data_out => X_in_1_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_1_V_strb_V_U_vld_out,
        ack_out => X_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_1_V_strb_V_U_apdone_blk);

    regslice_both_X_in_1_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_1_TLAST,
        vld_in => X_in_1_TVALID,
        ack_in => regslice_both_X_in_1_V_last_V_U_ack_in,
        data_out => X_in_1_TLAST_int_regslice,
        vld_out => regslice_both_X_in_1_V_last_V_U_vld_out,
        ack_out => X_in_1_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_1_V_last_V_U_apdone_blk);

    regslice_both_X_in_2_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_2_TDATA,
        vld_in => X_in_2_TVALID,
        ack_in => regslice_both_X_in_2_V_data_V_U_ack_in,
        data_out => X_in_2_TDATA_int_regslice,
        vld_out => X_in_2_TVALID_int_regslice,
        ack_out => X_in_2_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_2_V_data_V_U_apdone_blk);

    regslice_both_X_in_2_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_2_TKEEP,
        vld_in => X_in_2_TVALID,
        ack_in => regslice_both_X_in_2_V_keep_V_U_ack_in,
        data_out => X_in_2_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_2_V_keep_V_U_vld_out,
        ack_out => X_in_2_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_2_V_keep_V_U_apdone_blk);

    regslice_both_X_in_2_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_2_TSTRB,
        vld_in => X_in_2_TVALID,
        ack_in => regslice_both_X_in_2_V_strb_V_U_ack_in,
        data_out => X_in_2_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_2_V_strb_V_U_vld_out,
        ack_out => X_in_2_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_2_V_strb_V_U_apdone_blk);

    regslice_both_X_in_2_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_2_TLAST,
        vld_in => X_in_2_TVALID,
        ack_in => regslice_both_X_in_2_V_last_V_U_ack_in,
        data_out => X_in_2_TLAST_int_regslice,
        vld_out => regslice_both_X_in_2_V_last_V_U_vld_out,
        ack_out => X_in_2_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_2_V_last_V_U_apdone_blk);

    regslice_both_X_in_3_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_3_TDATA,
        vld_in => X_in_3_TVALID,
        ack_in => regslice_both_X_in_3_V_data_V_U_ack_in,
        data_out => X_in_3_TDATA_int_regslice,
        vld_out => X_in_3_TVALID_int_regslice,
        ack_out => X_in_3_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_3_V_data_V_U_apdone_blk);

    regslice_both_X_in_3_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_3_TKEEP,
        vld_in => X_in_3_TVALID,
        ack_in => regslice_both_X_in_3_V_keep_V_U_ack_in,
        data_out => X_in_3_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_3_V_keep_V_U_vld_out,
        ack_out => X_in_3_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_3_V_keep_V_U_apdone_blk);

    regslice_both_X_in_3_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_3_TSTRB,
        vld_in => X_in_3_TVALID,
        ack_in => regslice_both_X_in_3_V_strb_V_U_ack_in,
        data_out => X_in_3_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_3_V_strb_V_U_vld_out,
        ack_out => X_in_3_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_3_V_strb_V_U_apdone_blk);

    regslice_both_X_in_3_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_3_TLAST,
        vld_in => X_in_3_TVALID,
        ack_in => regslice_both_X_in_3_V_last_V_U_ack_in,
        data_out => X_in_3_TLAST_int_regslice,
        vld_out => regslice_both_X_in_3_V_last_V_U_vld_out,
        ack_out => X_in_3_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_3_V_last_V_U_apdone_blk);

    regslice_both_X_in_4_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_4_TDATA,
        vld_in => X_in_4_TVALID,
        ack_in => regslice_both_X_in_4_V_data_V_U_ack_in,
        data_out => X_in_4_TDATA_int_regslice,
        vld_out => X_in_4_TVALID_int_regslice,
        ack_out => X_in_4_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_4_V_data_V_U_apdone_blk);

    regslice_both_X_in_4_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_4_TKEEP,
        vld_in => X_in_4_TVALID,
        ack_in => regslice_both_X_in_4_V_keep_V_U_ack_in,
        data_out => X_in_4_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_4_V_keep_V_U_vld_out,
        ack_out => X_in_4_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_4_V_keep_V_U_apdone_blk);

    regslice_both_X_in_4_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_4_TSTRB,
        vld_in => X_in_4_TVALID,
        ack_in => regslice_both_X_in_4_V_strb_V_U_ack_in,
        data_out => X_in_4_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_4_V_strb_V_U_vld_out,
        ack_out => X_in_4_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_4_V_strb_V_U_apdone_blk);

    regslice_both_X_in_4_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_4_TLAST,
        vld_in => X_in_4_TVALID,
        ack_in => regslice_both_X_in_4_V_last_V_U_ack_in,
        data_out => X_in_4_TLAST_int_regslice,
        vld_out => regslice_both_X_in_4_V_last_V_U_vld_out,
        ack_out => X_in_4_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_4_V_last_V_U_apdone_blk);

    regslice_both_X_in_5_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_5_TDATA,
        vld_in => X_in_5_TVALID,
        ack_in => regslice_both_X_in_5_V_data_V_U_ack_in,
        data_out => X_in_5_TDATA_int_regslice,
        vld_out => X_in_5_TVALID_int_regslice,
        ack_out => X_in_5_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_5_V_data_V_U_apdone_blk);

    regslice_both_X_in_5_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_5_TKEEP,
        vld_in => X_in_5_TVALID,
        ack_in => regslice_both_X_in_5_V_keep_V_U_ack_in,
        data_out => X_in_5_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_5_V_keep_V_U_vld_out,
        ack_out => X_in_5_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_5_V_keep_V_U_apdone_blk);

    regslice_both_X_in_5_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_5_TSTRB,
        vld_in => X_in_5_TVALID,
        ack_in => regslice_both_X_in_5_V_strb_V_U_ack_in,
        data_out => X_in_5_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_5_V_strb_V_U_vld_out,
        ack_out => X_in_5_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_5_V_strb_V_U_apdone_blk);

    regslice_both_X_in_5_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_5_TLAST,
        vld_in => X_in_5_TVALID,
        ack_in => regslice_both_X_in_5_V_last_V_U_ack_in,
        data_out => X_in_5_TLAST_int_regslice,
        vld_out => regslice_both_X_in_5_V_last_V_U_vld_out,
        ack_out => X_in_5_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_5_V_last_V_U_apdone_blk);

    regslice_both_X_in_6_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_6_TDATA,
        vld_in => X_in_6_TVALID,
        ack_in => regslice_both_X_in_6_V_data_V_U_ack_in,
        data_out => X_in_6_TDATA_int_regslice,
        vld_out => X_in_6_TVALID_int_regslice,
        ack_out => X_in_6_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_6_V_data_V_U_apdone_blk);

    regslice_both_X_in_6_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_6_TKEEP,
        vld_in => X_in_6_TVALID,
        ack_in => regslice_both_X_in_6_V_keep_V_U_ack_in,
        data_out => X_in_6_TKEEP_int_regslice,
        vld_out => regslice_both_X_in_6_V_keep_V_U_vld_out,
        ack_out => X_in_6_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_6_V_keep_V_U_apdone_blk);

    regslice_both_X_in_6_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_6_TSTRB,
        vld_in => X_in_6_TVALID,
        ack_in => regslice_both_X_in_6_V_strb_V_U_ack_in,
        data_out => X_in_6_TSTRB_int_regslice,
        vld_out => regslice_both_X_in_6_V_strb_V_U_vld_out,
        ack_out => X_in_6_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_6_V_strb_V_U_apdone_blk);

    regslice_both_X_in_6_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => X_in_6_TLAST,
        vld_in => X_in_6_TVALID,
        ack_in => regslice_both_X_in_6_V_last_V_U_ack_in,
        data_out => X_in_6_TLAST_int_regslice,
        vld_out => regslice_both_X_in_6_V_last_V_U_vld_out,
        ack_out => X_in_6_TREADY_int_regslice,
        apdone_blk => regslice_both_X_in_6_V_last_V_U_apdone_blk);

    regslice_both_output_r_V_data_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => output_r_TDATA_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => output_r_TREADY_int_regslice,
        data_out => output_r_TDATA,
        vld_out => regslice_both_output_r_V_data_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_data_V_U_apdone_blk);

    regslice_both_output_r_V_keep_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TKEEP_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_keep_V_U_ack_in_dummy,
        data_out => output_r_TKEEP,
        vld_out => regslice_both_output_r_V_keep_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_keep_V_U_apdone_blk);

    regslice_both_output_r_V_strb_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TSTRB_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_strb_V_U_ack_in_dummy,
        data_out => output_r_TSTRB,
        vld_out => regslice_both_output_r_V_strb_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_strb_V_U_apdone_blk);

    regslice_both_output_r_V_last_V_U : component multi_lms_module_regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => d_in_TLAST_int_regslice,
        vld_in => output_r_TVALID_int_regslice,
        ack_in => regslice_both_output_r_V_last_V_U_ack_in_dummy,
        data_out => output_r_TLAST,
        vld_out => regslice_both_output_r_V_last_V_U_vld_out,
        ack_out => output_r_TREADY,
        apdone_blk => regslice_both_output_r_V_last_V_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            when others =>  
                ap_NS_iter0_fsm <= "X";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state2 => 
                if (((ap_const_boolean_0 = ap_block_state2_pp0_stage0_iter1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                elsif (((ap_const_boolean_0 = ap_block_state2_pp0_stage0_iter1) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state1) or ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state2;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XX";
        end case;
    end process;

    X_in_0_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_0_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_0_TDATA_blk_n <= X_in_0_TVALID_int_regslice;
        else 
            X_in_0_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_0_TREADY <= regslice_both_X_in_0_V_data_V_U_ack_in;

    X_in_0_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_0_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_0_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    X_in_1_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_1_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_1_TDATA_blk_n <= X_in_1_TVALID_int_regslice;
        else 
            X_in_1_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_1_TREADY <= regslice_both_X_in_1_V_data_V_U_ack_in;

    X_in_1_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_1_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_1_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    X_in_2_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_2_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_2_TDATA_blk_n <= X_in_2_TVALID_int_regslice;
        else 
            X_in_2_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_2_TREADY <= regslice_both_X_in_2_V_data_V_U_ack_in;

    X_in_2_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_2_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_2_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    X_in_3_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_3_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_3_TDATA_blk_n <= X_in_3_TVALID_int_regslice;
        else 
            X_in_3_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_3_TREADY <= regslice_both_X_in_3_V_data_V_U_ack_in;

    X_in_3_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_3_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_3_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    X_in_4_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_4_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_4_TDATA_blk_n <= X_in_4_TVALID_int_regslice;
        else 
            X_in_4_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_4_TREADY <= regslice_both_X_in_4_V_data_V_U_ack_in;

    X_in_4_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_4_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_4_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    X_in_5_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_5_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_5_TDATA_blk_n <= X_in_5_TVALID_int_regslice;
        else 
            X_in_5_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_5_TREADY <= regslice_both_X_in_5_V_data_V_U_ack_in;

    X_in_5_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_5_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_5_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    X_in_6_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, X_in_6_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            X_in_6_TDATA_blk_n <= X_in_6_TVALID_int_regslice;
        else 
            X_in_6_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    X_in_6_TREADY <= regslice_both_X_in_6_V_data_V_U_ack_in;

    X_in_6_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            X_in_6_TREADY_int_regslice <= ap_const_logic_1;
        else 
            X_in_6_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    and_ln37_fu_349_p2 <= (xor_ln37_fu_343_p2 and tmp_1_fu_335_p3);
    and_ln38_fu_417_p2 <= (xor_ln38_fu_411_p2 and tmp_3_fu_403_p3);
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter1_fsm_state2 <= ap_CS_iter1_fsm(1);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state2_blk_assign_proc : process(ap_block_state2_pp0_stage0_iter1)
    begin
        if ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1)) then 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(d_in_TVALID_int_regslice, X_in_0_TVALID_int_regslice, X_in_1_TVALID_int_regslice, X_in_2_TVALID_int_regslice, X_in_3_TVALID_int_regslice, X_in_4_TVALID_int_regslice, X_in_5_TVALID_int_regslice, X_in_6_TVALID_int_regslice, output_r_TREADY_int_regslice)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (ap_const_logic_0 = X_in_6_TVALID_int_regslice) or (ap_const_logic_0 = X_in_5_TVALID_int_regslice) or (ap_const_logic_0 = X_in_4_TVALID_int_regslice) or (ap_const_logic_0 = X_in_3_TVALID_int_regslice) or (ap_const_logic_0 = X_in_2_TVALID_int_regslice) or (ap_const_logic_0 = X_in_1_TVALID_int_regslice) or (ap_const_logic_0 = X_in_0_TVALID_int_regslice) or (d_in_TVALID_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state2_pp0_stage0_iter1_assign_proc : process(regslice_both_output_r_V_data_V_U_apdone_blk, output_r_TREADY_int_regslice)
    begin
                ap_block_state2_pp0_stage0_iter1 <= ((output_r_TREADY_int_regslice = ap_const_logic_0) or (regslice_both_output_r_V_data_V_U_apdone_blk = ap_const_logic_1));
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;


    d_in_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, d_in_TVALID_int_regslice)
    begin
        if ((ap_const_logic_1 = ap_CS_iter0_fsm_state1)) then 
            d_in_TDATA_blk_n <= d_in_TVALID_int_regslice;
        else 
            d_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    d_in_TREADY <= regslice_both_d_in_V_data_V_U_ack_in;

    d_in_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            d_in_TREADY_int_regslice <= ap_const_logic_1;
        else 
            d_in_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    out_tmp_data_M_imag_fu_437_p3 <= 
        select_ln38_fu_429_p3 when (xor_ln38_1_fu_423_p2(0) = '1') else 
        trunc_ln38_fu_399_p1;
    out_tmp_data_M_real_fu_369_p3 <= 
        select_ln37_fu_361_p3 when (xor_ln37_1_fu_355_p2(0) = '1') else 
        trunc_ln37_fu_331_p1;

    output_r_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, output_r_TREADY_int_regslice)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state2) or (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            output_r_TDATA_blk_n <= output_r_TREADY_int_regslice;
        else 
            output_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    output_r_TDATA_int_regslice <= (out_tmp_data_M_imag_fu_437_p3 & out_tmp_data_M_real_fu_369_p3);
    output_r_TVALID <= regslice_both_output_r_V_data_V_U_vld_out;

    output_r_TVALID_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state2, ap_block_state1_pp0_stage0_iter0, ap_block_state2_pp0_stage0_iter1)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or ((ap_const_boolean_1 = ap_block_state2_pp0_stage0_iter1) and (ap_const_logic_1 = ap_CS_iter1_fsm_state2)))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then 
            output_r_TVALID_int_regslice <= ap_const_logic_1;
        else 
            output_r_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    select_ln37_fu_361_p3 <= 
        ap_const_lv16_7FFF when (and_ln37_fu_349_p2(0) = '1') else 
        ap_const_lv16_8000;
    select_ln38_fu_429_p3 <= 
        ap_const_lv16_7FFF when (and_ln38_fu_417_p2(0) = '1') else 
        ap_const_lv16_8000;
        sext_ln37_1_fu_313_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln30_fu_295_p1),17));

        sext_ln37_fu_309_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_fu_277_p1),17));

        sext_ln38_1_fu_381_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln30_1_fu_299_p4),17));

        sext_ln38_fu_377_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln27_1_fu_281_p4),17));

    sub_ln37_fu_317_p2 <= std_logic_vector(signed(sext_ln37_fu_309_p1) - signed(sext_ln37_1_fu_313_p1));
    sub_ln38_fu_385_p2 <= std_logic_vector(signed(sext_ln38_fu_377_p1) - signed(sext_ln38_1_fu_381_p1));
    tmp_1_fu_335_p3 <= sub_ln37_fu_317_p2(15 downto 15);
    tmp_2_fu_391_p3 <= sub_ln38_fu_385_p2(16 downto 16);
    tmp_3_fu_403_p3 <= sub_ln38_fu_385_p2(15 downto 15);
    tmp_fu_323_p3 <= sub_ln37_fu_317_p2(16 downto 16);
    trunc_ln27_1_fu_281_p4 <= d_in_TDATA_int_regslice(31 downto 16);
    trunc_ln27_fu_277_p1 <= d_in_TDATA_int_regslice(16 - 1 downto 0);
    trunc_ln30_1_fu_299_p4 <= X_in_0_TDATA_int_regslice(31 downto 16);
    trunc_ln30_fu_295_p1 <= X_in_0_TDATA_int_regslice(16 - 1 downto 0);
    trunc_ln37_fu_331_p1 <= sub_ln37_fu_317_p2(16 - 1 downto 0);
    trunc_ln38_fu_399_p1 <= sub_ln38_fu_385_p2(16 - 1 downto 0);
    xor_ln37_1_fu_355_p2 <= (tmp_fu_323_p3 xor tmp_1_fu_335_p3);
    xor_ln37_fu_343_p2 <= (tmp_fu_323_p3 xor ap_const_lv1_1);
    xor_ln38_1_fu_423_p2 <= (tmp_3_fu_403_p3 xor tmp_2_fu_391_p3);
    xor_ln38_fu_411_p2 <= (tmp_2_fu_391_p3 xor ap_const_lv1_1);
end behav;
